# Generated by Django 4.2.4 on 2023-08-23 19:09

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('dividendo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preco_medio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data', models.DateField(default=datetime.date(2023, 8, 23), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 23))])),
                ('categoria', models.CharField(choices=[('Papéis', 'Papéis'), ('Shoppings', 'Shoppings'), ('Lajes Corporativas', 'Lajes Corporativas'), ('Galpões Logísticos', 'Galpões Logísticos'), ('Hotéis', 'Hotéis'), ('Educacional', 'Educacional'), ('Hospitais', 'Hospitais'), ('Agências Bancárias', 'Agências Bancárias'), ('Fundos', 'Fundos'), ('Desenvolvimento Imobiliário', 'Desenvolvimento Imobiliário'), ('Recebíveis Imobiliários', 'Recebíveis Imobiliários'), ('Hibrido', 'Hibrido'), ('Outros', 'Outros')], default='Outros', max_length=100)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fundos Imobiliários',
            },
        ),
        migrations.CreateModel(
            name='Criptos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('dividendo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preco_medio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data', models.DateField(default=datetime.date(2023, 8, 23), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 23))])),
                ('categoria', models.CharField(choices=[('Stablecoin', 'Stablecoin'), ('Altcoin', 'Altcoin'), ('Defi', 'Defi'), ('Protocol token', 'Protocol Token'), ('Security token', 'Security Token'), ('Gaming token', 'Gaming Token'), ('Energy token', 'Energy Token'), ('Exchange token', 'Exchange Token'), ('Utility token', 'Utility Token'), ('Fan token', 'Fan Token'), ('Web 3.0', 'Web 3 0'), ('Privacy coin', 'Privacy Coin'), ('Outros', 'Outros')], default='Outros', max_length=100)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Criptos',
            },
        ),
        migrations.CreateModel(
            name='Bdrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('dividendo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preco_medio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data', models.DateField(default=datetime.date(2023, 8, 23), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 23))])),
                ('categoria', models.CharField(choices=[('Nível 1', 'Nível 1'), ('Nível 2', 'Nível 2'), ('Nível 3', 'Nível 3'), ('Outros', 'Outros')], default='Outros', max_length=100)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Brazilian Depositary Receipts',
            },
        ),
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('dividendo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preco_medio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data', models.DateField(default=datetime.date(2023, 8, 23), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 23))])),
                ('categoria', models.CharField(choices=[('Ordinárias', 'Ordinarias'), ('Preferenciais', 'Preferenciais'), ('Especiais', 'Especiais'), ('Outros', 'Outros')], default='Outros', max_length=100)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ações',
            },
        ),
    ]
