# Generated by Django 4.2.4 on 2023-08-25 17:37

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investimentos', '0003_historicocompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendasFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('dividendo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preco_medio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data', models.DateField(default=datetime.date(2023, 8, 25), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 25))])),
                ('categoria', models.CharField(choices=[('Tesouro Selic', 'Tesouro Selic'), ('Tesouro Prefixado', 'Tesouro Prefixado'), ('Tesouro IPCA', 'Tesouro Ipca'), ('CDB', 'Cdb'), ('LCI', 'Lci'), ('LCA', 'Lca'), ('LC', 'Lc'), ('Debêntures', 'Debentures'), ('Fundos de Renda Fixa', 'Fundos Rf'), ('CRI', 'Cri'), ('CRA', 'Cra'), ('Outros', 'Outros')], default='Outros', max_length=100)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Renda Fixa',
            },
        ),
        migrations.AlterField(
            model_name='acoes',
            name='data',
            field=models.DateField(default=datetime.date(2023, 8, 25), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 25))]),
        ),
        migrations.AlterField(
            model_name='bdrs',
            name='data',
            field=models.DateField(default=datetime.date(2023, 8, 25), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 25))]),
        ),
        migrations.AlterField(
            model_name='criptos',
            name='data',
            field=models.DateField(default=datetime.date(2023, 8, 25), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 25))]),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='data',
            field=models.DateField(default=datetime.date(2023, 8, 25), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 25))]),
        ),
        migrations.DeleteModel(
            name='RendaFixa',
        ),
    ]
