# Generated by Django 4.2.4 on 2023-08-28 12:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0004_rendasfixa_alter_acoes_data_alter_bdrs_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acoes',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='bdrs',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='criptos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='fiis',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='rendasfixa',
            name='nome',
        ),
        migrations.AlterField(
            model_name='acoes',
            name='data',
            field=models.DateField(default=datetime.date(2023, 8, 28), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 28))]),
        ),
        migrations.AlterField(
            model_name='bdrs',
            name='data',
            field=models.DateField(default=datetime.date(2023, 8, 28), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 28))]),
        ),
        migrations.AlterField(
            model_name='criptos',
            name='data',
            field=models.DateField(default=datetime.date(2023, 8, 28), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 28))]),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='data',
            field=models.DateField(default=datetime.date(2023, 8, 28), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 28))]),
        ),
        migrations.AlterField(
            model_name='rendasfixa',
            name='data',
            field=models.DateField(default=datetime.date(2023, 8, 28), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 28))]),
        ),
    ]
