# Generated by Django 4.2.4 on 2023-09-15 18:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0006_alter_bdrs_options_alter_acoes_data_alter_bdrs_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimaVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='acoes',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 15), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 15))]),
        ),
        migrations.AlterField(
            model_name='bdrs',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 15), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 15))]),
        ),
        migrations.AlterField(
            model_name='criptos',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 15), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 15))]),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='categoria',
            field=models.CharField(choices=[('Papéis', 'Papéis'), ('Shoppings', 'Shoppings'), ('Lajes Corporativas', 'Lajes Corporativas'), ('Galpões Logísticos', 'Galpões Logísticos'), ('Agro', 'Agro'), ('Hotéis', 'Hotéis'), ('Educacional', 'Educacional'), ('Hospitais', 'Hospitais'), ('Agências Bancárias', 'Agências Bancárias'), ('Fundos', 'Fundos'), ('Desenvolvimento Imobiliário', 'Desenvolvimento Imobiliário'), ('Recebíveis Imobiliários', 'Recebíveis Imobiliários'), ('Hibrido', 'Hibrido'), ('Outros', 'Outros')], default='Outros', max_length=100),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 15), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 15))]),
        ),
        migrations.AlterField(
            model_name='rendasfixa',
            name='categoria',
            field=models.CharField(choices=[('Conta Remunerada', 'Conta Remunerada'), ('Tesouro Selic', 'Tesouro Selic'), ('Tesouro Prefixado', 'Tesouro Prefixado'), ('Tesouro IPCA', 'Tesouro Ipca'), ('CDB', 'Cdb'), ('LCI', 'Lci'), ('LCA', 'Lca'), ('LC', 'Lc'), ('Debêntures', 'Debentures'), ('Fundos de Renda Fixa', 'Fundos Rf'), ('CRI', 'Cri'), ('CRA', 'Cra'), ('Outros', 'Outros')], default='Outros', max_length=100),
        ),
        migrations.AlterField(
            model_name='rendasfixa',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 15), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 15))]),
        ),
    ]
