# Generated by Django 4.2.4 on 2023-09-19 17:29

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investimentos', '0008_alter_acoes_data_alter_bdrs_data_alter_criptos_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimaverificacao',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ultimaverificacao',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 19), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 19))]),
        ),
        migrations.AlterField(
            model_name='bdrs',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 19), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 19))]),
        ),
        migrations.AlterField(
            model_name='criptos',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 19), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 19))]),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 19), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 19))]),
        ),
        migrations.AlterField(
            model_name='rendasfixa',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 19), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 19))]),
        ),
    ]
