# Generated by Django 4.2.4 on 2023-09-22 14:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0010_alter_acoes_data_alter_bdrs_data_alter_criptos_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 22), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 22))]),
        ),
        migrations.AlterField(
            model_name='bdrs',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 22), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 22))]),
        ),
        migrations.AlterField(
            model_name='criptos',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 22), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 22))]),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 22), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 22))]),
        ),
        migrations.AlterField(
            model_name='rendasfixa',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 22), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 22))]),
        ),
    ]
