# Generated by Django 4.2.4 on 2023-09-25 17:38

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0012_fiisconsolidadas_criptosconsolidadas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiisconsolidadas',
            options={'verbose_name_plural': 'Fundos Imobiliários consolidados'},
        ),
        migrations.AlterField(
            model_name='acoes',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 25), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 25))]),
        ),
        migrations.AlterField(
            model_name='acoesconsolidadas',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='bdrs',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 25), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 25))]),
        ),
        migrations.AlterField(
            model_name='bdrsconsolidadas',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='criptos',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 25), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 25))]),
        ),
        migrations.AlterField(
            model_name='criptosconsolidadas',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 25), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 25))]),
        ),
        migrations.AlterField(
            model_name='fiisconsolidadas',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='rendasfixa',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 25), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 25))]),
        ),
    ]
