# Generated by Django 4.2.4 on 2023-09-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0013_alter_fiisconsolidadas_options_alter_acoes_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptos',
            name='quantidade',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=14),
        ),
    ]
