# Generated by Django 4.2.4 on 2023-09-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0014_alter_criptos_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='quantidade',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='bdrs',
            name='quantidade',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='quantidade',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='rendasfixa',
            name='quantidade',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=14),
        ),
    ]
