# Generated by Django 4.2.4 on 2023-10-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0023_alter_acoes_quantidade_alter_bdrs_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bdrs',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fiis',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rendasfixa',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
