# Generated by Django 4.2.4 on 2023-10-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0024_alter_acoes_quantidade_alter_bdrs_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocompra',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
