# Generated by Django 4.2.4 on 2023-10-19 16:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0026_rendasfixaconsolidadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptosconsolidadas',
            name='quantidade',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))]),
        ),
    ]
