# Generated by Django 4.2.4 on 2023-10-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0027_alter_criptosconsolidadas_quantidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RendasFixaConsolidadas',
        ),
    ]
