# Generated by Django 4.2.4 on 2023-11-03 15:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0028_delete_rendasfixaconsolidadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdrsconsolidadas',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bdrsconsolidadas',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='criptosconsolidadas',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='criptosconsolidadas',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='fiisconsolidadas',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fiisconsolidadas',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='acoes',
            name='valor_mercado',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='bdrs',
            name='valor_mercado',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='criptos',
            name='valor_mercado',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='fiis',
            name='valor_mercado',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='rendasfixa',
            name='valor_mercado',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.DeleteModel(
            name='AcoesConsolidadas',
        ),
        migrations.DeleteModel(
            name='BdrsConsolidadas',
        ),
        migrations.DeleteModel(
            name='CriptosConsolidadas',
        ),
        migrations.DeleteModel(
            name='FiisConsolidadas',
        ),
    ]
