# Generated by Django 4.2.4 on 2023-11-03 19:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0030_alter_acoes_valor_alter_acoes_valor_mercado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acoes',
            name='valor_total_mercado',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bdrs',
            name='valor_total_mercado',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='criptos',
            name='valor_total_mercado',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='fiis',
            name='valor_total_mercado',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='rendasfixa',
            name='valor_total_mercado',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10),
        ),
    ]
