# Generated by Django 4.2.4 on 2023-11-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0033_alter_acoes_valor_mercado_alter_bdrs_valor_mercado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendasfixa',
            name='preco_medio',
        ),
        migrations.RemoveField(
            model_name='rendasfixa',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='rendasfixa',
            name='valor_mercado',
        ),
        migrations.RemoveField(
            model_name='rendasfixa',
            name='valor_total_mercado',
        ),
    ]
