# Generated by Django 4.2.4 on 2023-08-12 19:50

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_gasto', models.CharField(choices=[('Aluguel', 'Aluguel'), ('Mercado', 'Mercado'), ('Luz', 'Luz'), ('Água', 'Água'), ('Gasolina', 'Gasolina'), ('Pet', 'Pet'), ('Lanches', 'Lanches'), ('Saúde', 'Saude'), ('Transporte', 'Transporte'), ('Educação', 'Educacao'), ('Assinaturas', 'Assinaturas'), ('Viagens', 'Viajens'), ('Vestuário', 'Vestuario'), ('Investimentos', 'Investimentos'), ('Doações', 'Doacoes'), ('Carro', 'Carro'), ('Imóveis', 'Imoveis'), ('Seguros', 'Seguros'), ('Presentes', 'Presentes'), ('Restaurantes', 'Restaurantes'), ('Casa', 'Casa'), ('Outros', 'Outros')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ChoicesRendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_renda', models.CharField(choices=[('Salário', 'Salario'), ('Ações', 'Acoes'), ('BDRs', 'Bdrs'), ('FIIs', 'Fiis'), ('Outros', 'Outros')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento', models.CharField(choices=[('Depósito', 'Deposito'), ('Dinheiro', 'Dinheiro'), ('Débito', 'Debito'), ('Crédito', 'Credito'), ('Pix', 'Pix'), ('Outros', 'Outros')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descricao', models.TextField(default='')),
                ('data', models.DateField(default=datetime.date(2023, 8, 12), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 12))])),
                ('metodo_pagamento', models.CharField(choices=[('Depósito', 'Deposito'), ('Dinheiro', 'Dinheiro'), ('Débito', 'Debito'), ('Crédito', 'Credito'), ('Pix', 'Pix'), ('Outros', 'Outros')], default='Outros', max_length=100)),
                ('categoria', models.CharField(choices=[('Salário', 'Salario'), ('Ações', 'Acoes'), ('BDRs', 'Bdrs'), ('FIIs', 'Fiis'), ('Outros', 'Outros')], default='Outros', max_length=100)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rendas',
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descricao', models.TextField(default='')),
                ('data', models.DateField(default=datetime.date(2023, 8, 12), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 12))])),
                ('metodo_pagamento', models.CharField(choices=[('Depósito', 'Deposito'), ('Dinheiro', 'Dinheiro'), ('Débito', 'Debito'), ('Crédito', 'Credito'), ('Pix', 'Pix'), ('Outros', 'Outros')], default='Outros', max_length=100)),
                ('categoria', models.CharField(choices=[('Aluguel', 'Aluguel'), ('Mercado', 'Mercado'), ('Luz', 'Luz'), ('Água', 'Água'), ('Gasolina', 'Gasolina'), ('Pet', 'Pet'), ('Lanches', 'Lanches'), ('Saúde', 'Saude'), ('Transporte', 'Transporte'), ('Educação', 'Educacao'), ('Assinaturas', 'Assinaturas'), ('Viagens', 'Viajens'), ('Vestuário', 'Vestuario'), ('Investimentos', 'Investimentos'), ('Doações', 'Doacoes'), ('Carro', 'Carro'), ('Imóveis', 'Imoveis'), ('Seguros', 'Seguros'), ('Presentes', 'Presentes'), ('Restaurantes', 'Restaurantes'), ('Casa', 'Casa'), ('Outros', 'Outros')], default='Outros', max_length=100)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
