# Generated by Django 4.2.4 on 2023-08-31 17:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendas_gastos', '0015_alter_gastos_valor_alter_rendas_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='categoria',
            field=models.CharField(choices=[('Aluguel', 'Aluguel'), ('Mercado', 'Mercado'), ('Luz', 'Luz'), ('Água', 'Água'), ('Gasolina', 'Gasolina'), ('Pet', 'Pet'), ('Lanches', 'Lanches'), ('Saúde', 'Saude'), ('Transporte', 'Transporte'), ('Educação', 'Educacao'), ('Assinaturas', 'Assinaturas'), ('Viagens', 'Viajens'), ('Vestuário', 'Vestuario'), ('Investimentos', 'Investimentos'), ('Doações', 'Doacoes'), ('Carro', 'Carro'), ('Seguros', 'Seguros'), ('Restaurante', 'Restaurante'), ('Casa', 'Casa'), ('Outros', 'Outros')], default='Outros', max_length=100),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='data',
            field=models.DateField(default=datetime.date(2023, 8, 31), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 31))]),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Depósito', 'Deposito'), ('Dinheiro', 'Dinheiro'), ('Débito', 'Debito'), ('Crédito', 'Credito'), ('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Outros', 'Outros')], default='Outros', max_length=100),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='categoria',
            field=models.CharField(choices=[('Salário', 'Salario'), ('Ações', 'Acoes'), ('BDRs', 'Bdrs'), ('FIIs', 'Fiis'), ('Renda Fixa', 'Renda Fixa'), ('Outros', 'Outros')], default='Outros', max_length=100),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='data',
            field=models.DateField(default=datetime.date(2023, 8, 31), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 31))]),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Depósito', 'Deposito'), ('Dinheiro', 'Dinheiro'), ('Débito', 'Debito'), ('Crédito', 'Credito'), ('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Outros', 'Outros')], default='Outros', max_length=100),
        ),
    ]
