# Generated by Django 4.2.4 on 2023-09-15 18:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendas_gastos', '0016_alter_gastos_categoria_alter_gastos_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='categoria',
            field=models.CharField(choices=[('Aluguel', 'Aluguel'), ('Mercado', 'Mercado'), ('Luz', 'Luz'), ('Água', 'Água'), ('Gasolina', 'Gasolina'), ('Pet', 'Pet'), ('Internet', 'Internet'), ('Celular', 'Celular'), ('Lanches', 'Lanches'), ('Saúde', 'Saúde'), ('Transporte', 'Transporte'), ('Educação', 'Educação'), ('Assinaturas', 'Assinaturas'), ('Viagens', 'Viajens'), ('Vestuário', 'Vestuário'), ('Investimentos', 'Investimentos'), ('Doações', 'Doações'), ('Carro', 'Carro'), ('Seguros', 'Seguros'), ('Restaurante', 'Restaurante'), ('Casa', 'Casa'), ('Outros', 'Outros')], default='Outros', max_length=100),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 15), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 15))]),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Depósito', 'Depósito'), ('Dinheiro', 'Dinheiro'), ('Débito', 'Débito'), ('Crédito', 'Crédito'), ('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Outros', 'Outros')], default='Outros', max_length=100),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='categoria',
            field=models.CharField(choices=[('Salário', 'Salário'), ('Ações', 'Ações'), ('BDRs', 'Bdrs'), ('FIIs', 'Fiis'), ('Renda Fixa', 'Renda Fixa'), ('Cashback', 'Cashback'), ('Outros', 'Outros')], default='Outros', max_length=100),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 15), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 15))]),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Depósito', 'Depósito'), ('Dinheiro', 'Dinheiro'), ('Débito', 'Débito'), ('Crédito', 'Crédito'), ('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Outros', 'Outros')], default='Outros', max_length=100),
        ),
    ]
