# Generated by Django 4.2.4 on 2023-09-19 17:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendas_gastos', '0018_alter_gastos_data_alter_rendas_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 19), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 19))]),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='data',
            field=models.DateField(default=datetime.date(2023, 9, 19), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 19))]),
        ),
    ]
