# Generated by Django 4.2.4 on 2023-10-06 18:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendas_gastos', '0023_alter_gastos_data_alter_rendas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='data',
            field=models.DateField(default=datetime.date(2023, 10, 6), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 10, 6))]),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='data',
            field=models.DateField(default=datetime.date(2023, 10, 6), validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 10, 6))]),
        ),
    ]
