# Generated by Django 4.2.4 on 2023-10-06 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rendas_gastos', '0024_alter_gastos_data_alter_rendas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
