# Generated by Django 4.2.4 on 2023-11-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendas_gastos', '0027_gastos_descricao_rendas_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='descricao',
            field=models.CharField(blank=True, default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='descricao',
            field=models.CharField(blank=True, default='-', max_length=20, null=True),
        ),
    ]
