# Generated by Django 4.2.4 on 2023-11-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendas_gastos', '0028_alter_gastos_descricao_alter_rendas_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='categoria',
            field=models.CharField(choices=[('Água', 'Água'), ('Aluguel', 'Aluguel'), ('Assinaturas', 'Assinaturas'), ('Carro', 'Carro'), ('Casa', 'Casa'), ('Celular', 'Celular'), ('Condomínio', 'Condomínio'), ('Doações', 'Doações'), ('Educação', 'Educação'), ('Gás', 'Gás'), ('Gasolina', 'Gasolina'), ('Investimentos', 'Investimentos'), ('Internet', 'Internet'), ('Lanches', 'Lanches'), ('Lazer', 'Lazer'), ('Luz', 'Luz'), ('Mercado', 'Mercado'), ('Pet', 'Pet'), ('Presente', 'Presente'), ('Restaurante', 'Restaurante'), ('Saúde', 'Saúde'), ('Seguros', 'Seguros'), ('Transporte', 'Transporte'), ('Vestuário', 'Vestuário'), ('Viagens', 'Viagens'), ('Outros', 'Outros')], default='Outros', max_length=100),
        ),
    ]
