# Generated by Django 4.2.4 on 2023-12-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendas_gastos', '0029_alter_gastos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendas',
            name='categoria',
            field=models.CharField(choices=[('Salário', 'Salário'), ('VA_VR', 'Va Vr'), ('Freela', 'Freela'), ('Venda ativos', 'Venda Ativos'), ('Cashback', 'Cashback'), ('Proventos', 'Proventos'), ('Outros', 'Outros')], default='Outros', max_length=100),
        ),
    ]
